- name: Deploy Web Application
  hosts: db_and_web_server

  tasks:
    - name: Install dependencies
      apt:
        name:
          - python3
          - python3-setuptools
          - python3-dev
          - build-essential
          - python3-pip
          - python3-mysqldb
        state: present       

    - name: Include tasks to install and configure the database
      include_tasks: tasks/deploy_db.yml

    - name: Include tasks to install and configure the web-app
      include_tasks: tasks/deploy_web.yml
    