- name: Deploy Web Application
  hosts: db_and_web_server1,db_and_web_server2
  vars:
    db_name: employee_db
    db_usr: db_user
    db_pass: Passw0rd

  tasks:
    - name: Install dependencies
      apt:
        name:
          - python3
          - python3-setuptools
          - python3-dev
          - build-essential
          - python3-pip
          - python3-mysqldb
        state: present       

    - name: Install MySQL database
      apt:
        name:
          - mysql-server
          - mysql-client
        state: present

    - name: Start MySQL service
      shell: service mysql start
      # service:
      #   name: mysql
      #   state: started
      #   enabled: true

    - name: Create Application database
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create Application DB User
      mysql_user:
        name: "{{ db_usr }}"
        passwod: "{{ db_pass }}"
        state: present
        priv: '*.*:ALL'
        host: '%'
        login_unix_socket: /var/run/mysqld/mysqld.sock
    
    - name: Install python Flask dependencies
      pip:
        name: 
          - flask
          - flask-mysql
          - cryptography
        state: present
        executable: pip3
      
    - name: Copy web-server code
      copy:
        src: app.py
        dest: /opt/app.py

    - name: Run web-server
      shell: FLASK_APP=/opt/app.py flask run --host=0.0.0.0 &
