---
    - name: Install MySQL database
      apt:
        name:
          - mysql-server
          - mysql-client
        state: present

    - name: Start MySQL service
      shell: service mysql start
      # service:
      #   name: mysql
      #   state: started
      #   enabled: true

    - name: Create Application database
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create Application DB User
      mysql_user:
        name: "{{ db_usr }}"
        passwod: "{{ db_pass }}"
        state: present
        priv: '*.*:ALL'
        host: '%'
        login_unix_socket: /var/run/mysqld/mysqld.sock
